In [26]:
import torch
import PIL
import os
import numpy as np
from PIL import Image
from matplotlib import pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [27]:
path = r"C:\Users\bbfss\Desktop\Code\github\Denoising-CNN\dataset\干净信号txt"  # 干净文件夹目录
# path = r"C:\Users\bbfss\Desktop\Code\github\Denoising-CNN\dataset\带噪信号txt"  # 带噪文件夹目录
files = os.listdir(path)  # 得到文件夹下的所有文件名称
s = []
count = 0
for file in files:  # 遍历文件夹
    if not os.path.isdir(file):  # 判断是否是文件夹，不是文件夹才打开
        f = open(path + "/" + file);  # 打开文件
        iter_f = iter(f);  # 创建迭代器
        str1 = ""
        for line in iter_f:  # 遍历文件，一行行遍历，读取文本
            str1 = str1 + line
        s.append(str1)  # 每个文件的文本存到list中

In [28]:
a = []
for x in s:
    l = []
    for i in x.split('\n'):
        if i == '':
            continue;
        l.append(float(i))  # !!!!!为了防止失去精度
    a.append(np.array(l))
print(np.max(a))

1.92893887


In [29]:
print(a[0])
print(a[1])

# 归一化操作， 可以使用MinMaxScaler()中的inverse_transform方法还原
min_max_scaler = MinMaxScaler(feature_range=(0, 1))
a = min_max_scaler.fit_transform(a)


[0.         0.         0.         ... 0.00023251 0.00020236 0.00013161]
[ 0.0000e+00  0.0000e+00  0.0000e+00 ... -3.4157e-04 -1.9524e-04
 -1.8890e-05]


In [30]:
ph = []
for x in a:
    photo = np.zeros((1, 2000))
    #     photo[256][:][0]=x
    for i in range(2000):
        photo[0][i] = x[i]
    ph.append(photo.reshape(40, 50))
print(ph[0])
print(ph[1])

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.56299502 0.54021132 0.51279208 ... 0.4194217  0.42035687 0.41556479]
 [0.4151561  0.41557207 0.41507304 ... 0.40631359 0.40765515 0.40289452]
 [0.40402757 0.40451505 0.39934996 ... 0.53457563 0.59436787 0.67039501]]
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.56456462 0.54287245 0.51615066 ... 0.41469711 0.41641919 0.41303154]
 [0.41442654 0.4164555  0.4171134  ... 0.40130684 0.40348743 0.4000635 ]
 [0.40277804 0.40474394 0.40078423 ... 0.5311468  0.59093989 0.66767671]]


In [31]:
path = "C:/Users/bbfss/Desktop/Code/github/Denoising-CNN/dataset/干净灰度图/"
# path = "C:/Users/bbfss/Desktop/Code/github/Denoising-CNN/dataset/带噪灰度图/"
count = 0
for x in ph:
    count += 1
    new_im = Image.fromarray(x * 255.0)  # 实现array转化成图像
    num = str(count)
    new_im = new_im.convert('L')  # 将图像转化成灰度图
    new_im.save(path + 'train/img' + num + '.bmp')